# =============================================================================
# Partition-Aware Data Sources
# =============================================================================
data "aws_partition" "current" {}

locals {
  partition  = data.aws_partition.current.partition
  dns_suffix = data.aws_partition.current.dns_suffix
}

# IAM Role for Step Functions
resource "aws_iam_role" "step_functions" {
  name = "${var.project_name}-sfn-${var.environment}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "states.${local.dns_suffix}" }
    }]
  })

  tags = var.tags
}

resource "aws_iam_role_policy" "step_functions" {
  name = "sfn-policy"
  role = aws_iam_role.step_functions.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      # ecs:RunTask — scoped to this specific task-definition family (any revision) on this cluster.
      # Pattern: Resource = "<family_arn>:*" + Condition ArnEquals { ecs:cluster = <cluster_arn> }
      # Using arn_without_revision:* (not a revision-pinned ARN) avoids re-applying the policy on
      # every task-def revision bump while still restricting to this one family. AWS-documented
      # least-privilege pattern for Step Functions orchestrating ECS (same pattern as the
      # agents-orchestrator Lambda role, cf. commit 27917f4).
      {
        Effect   = "Allow"
        Action   = ["ecs:RunTask"]
        Resource = var.agent_task_definition_family_arn != "" ? "${var.agent_task_definition_family_arn}:*" : "*"
        Condition = {
          ArnEquals = { "ecs:cluster" = var.ecs_cluster_arn }
        }
      },
      # ecs:StopTask / DescribeTasks — the task ARN is only known at runtime (generated by
      # RunTask), so we must allow the task/* wildcard. Cluster condition keeps it scoped.
      {
        Effect   = "Allow"
        Action   = ["ecs:StopTask", "ecs:DescribeTasks"]
        Resource = "arn:${local.partition}:ecs:${var.aws_region}:*:task/*/*"
        Condition = {
          ArnEquals = { "ecs:cluster" = var.ecs_cluster_arn }
        }
      },
      # iam:PassRole — Step Functions must pass the task execution and task roles to ECS when
      # launching the agent task. Scoped to the two specific role ARNs, with a PassedToService
      # condition so these roles can only be passed to ECS tasks (not to arbitrary services).
      {
        Effect   = "Allow"
        Action   = ["iam:PassRole"]
        Resource = [var.agent_execution_role_arn, var.agent_task_role_arn]
        Condition = {
          StringEquals = {
            "iam:PassedToService" = "ecs-tasks.${local.dns_suffix}"
          }
        }
      },
      {
        Effect   = "Allow"
        Action   = ["events:PutTargets", "events:PutRule", "events:DescribeRule"]
        Resource = "arn:${local.partition}:events:${var.aws_region}:*:rule/StepFunctionsGetEventsForECSTaskRule"
      },
      # CloudWatch Logs permissions for Step Functions execution logging.
      # Two groups: (1) log-delivery management APIs (account-level, no resource scoping
      # supported) and (2) direct log-stream write APIs scoped to the SFN log group.
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogDelivery",
          "logs:GetLogDelivery",
          "logs:UpdateLogDelivery",
          "logs:DeleteLogDelivery",
          "logs:ListLogDeliveries",
          "logs:PutResourcePolicy",
          "logs:DescribeResourcePolicies",
          "logs:DescribeLogGroups"
        ]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "${aws_cloudwatch_log_group.step_functions.arn}:*"
      },
      {
        Effect   = "Allow"
        Action   = ["lambda:InvokeFunction"]
        Resource = [module.create_pr_lambda.lambda_function_arn]
      }
    ]
  })
}

# Create PR Lambda
module "create_pr_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 8.0"

  function_name = "${var.project_name}-create-pr-${var.environment}"
  handler       = "create-pr.handler"
  runtime       = "nodejs24.x"
  timeout       = 30

  source_path = [
    {
      path             = "${path.module}/../../../lambda/create-pr"
      npm_requirements = true
    }
  ]

  create_role = false
  lambda_role = aws_iam_role.create_pr.arn

  tags = var.tags
}

resource "aws_iam_role" "create_pr" {
  name = "${var.project_name}-create-pr-${var.environment}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "lambda.${local.dns_suffix}" }
    }]
  })

  tags = var.tags
}

resource "aws_iam_role_policy" "create_pr" {
  name = "create-pr-policy"
  role = aws_iam_role.create_pr.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = "arn:${local.partition}:logs:*:*:*"
      }
    ]
  })
}

# CloudWatch Log Group for Step Functions
resource "aws_cloudwatch_log_group" "step_functions" {
  name              = "/aws/stepfunctions/${var.project_name}-agent-workflow-${var.environment}"
  retention_in_days = var.environment == "prod" ? 30 : 7

  tags = var.tags
}

# Agent Workflow State Machine
resource "aws_sfn_state_machine" "agent_workflow" {
  name     = "${var.project_name}-agent-workflow-${var.environment}"
  role_arn = aws_iam_role.step_functions.arn

  logging_configuration {
    log_destination        = "${aws_cloudwatch_log_group.step_functions.arn}:*"
    include_execution_data = true
    level                  = "ERROR"
  }

  definition = jsonencode({
    Comment = "AI-DLC Agent Workflow Orchestration"
    StartAt = "RunInceptionAgent"
    States = {
      RunInceptionAgent = {
        Type     = "Task"
        Resource = "arn:${local.partition}:states:::ecs:runTask.sync"
        Parameters = {
          LaunchType     = "FARGATE"
          Cluster        = var.ecs_cluster_arn
          TaskDefinition = var.agent_task_definition_arn
          NetworkConfiguration = {
            AwsvpcConfiguration = {
              Subnets        = var.private_subnet_ids
              SecurityGroups = [var.agent_security_group_id]
              AssignPublicIp = "DISABLED"
            }
          }
          Overrides = {
            ContainerOverrides = [{
              Name = "agent"
              Environment = [
                { "Name" = "PROJECT_ID", "Value.$" = "$.projectId" },
                { "Name" = "AGENT_TYPE", "Value" = "inception" },
                { "Name" = "DESCRIPTION", "Value.$" = "$.description" },
                { "Name" = "GIT_REPO", "Value.$" = "$.gitRepo" },
                { "Name" = "USER_ID", "Value.$" = "$.userId" },
                { "Name" = "EXECUTION_ID", "Value.$" = "$$.Execution.Id" },
                { "Name" = "TASK_TOKEN", "Value.$" = "$$.Task.Token" }
              ]
            }]
          }
        }
        ResultPath = "$.inceptionResult"
        Next       = "GetInceptionOutput"
        Catch = [{
          ErrorEquals = ["States.ALL"]
          Next        = "WorkflowFailed"
          ResultPath  = "$.error"
        }]
      }

      GetInceptionOutput = {
        Type     = "Task"
        Resource = "arn:${local.partition}:states:::lambda:invoke"
        Parameters = {
          FunctionName = module.get_agent_output_lambda.lambda_function_arn
          Payload = {
            "executionId.$" = "$$.Execution.Id"
            "agentType"     = "inception"
          }
        }
        ResultSelector = {
          "tasks.$" = "$.Payload.tasks"
        }
        ResultPath = "$.inceptionOutput"
        Next       = "CheckTasks"
        Catch = [{
          ErrorEquals = ["States.ALL"]
          Next        = "RunReviewAgent"
          ResultPath  = "$.getOutputError"
        }]
      }

      CheckTasks = {
        Type = "Choice"
        Choices = [{
          Variable  = "$.inceptionOutput.tasks[0]"
          IsPresent = true
          Next      = "RunConstructionAgents"
        }]
        Default = "RunReviewAgent"
      }

      RunConstructionAgents = {
        Type           = "Map"
        ItemsPath      = "$.inceptionOutput.tasks"
        MaxConcurrency = 5
        Iterator = {
          StartAt = "RunConstructionAgent"
          States = {
            RunConstructionAgent = {
              Type     = "Task"
              Resource = "arn:${local.partition}:states:::ecs:runTask.sync"
              Parameters = {
                LaunchType     = "FARGATE"
                Cluster        = var.ecs_cluster_arn
                TaskDefinition = var.agent_task_definition_arn
                NetworkConfiguration = {
                  AwsvpcConfiguration = {
                    Subnets        = var.private_subnet_ids
                    SecurityGroups = [var.agent_security_group_id]
                    AssignPublicIp = "DISABLED"
                  }
                }
                Overrides = {
                  ContainerOverrides = [{
                    Name = "agent"
                    Environment = [
                      { "Name" = "PROJECT_ID", "Value.$" = "$.projectId" },
                      { "Name" = "AGENT_TYPE", "Value" = "construction" },
                      { "Name" = "TASK_ID", "Value.$" = "$.taskId" },
                      { "Name" = "EXECUTION_ID", "Value.$" = "$$.Execution.Id" },
                      { "Name" = "TASK_TOKEN", "Value.$" = "$$.Task.Token" },
                      { "Name" = "BRANCH", "Value.$" = "$.branch" },
                      { "Name" = "GIT_REPO", "Value.$" = "$.gitRepo" },
                      { "Name" = "GIT_TOKEN", "Value.$" = "$.gitToken" }
                    ]
                  }]
                }
              }
              End = true
              Retry = [{
                ErrorEquals     = ["States.TaskFailed"]
                IntervalSeconds = 30
                MaxAttempts     = 2
                BackoffRate     = 2
              }]
            }
          }
        }
        ResultPath = "$.constructionResults"
        Next       = "CreatePullRequest"
        Catch = [{
          ErrorEquals = ["States.ALL"]
          Next        = "WorkflowFailed"
          ResultPath  = "$.error"
        }]
      }

      CreatePullRequest = {
        Type     = "Task"
        Resource = "arn:${local.partition}:states:::lambda:invoke"
        Parameters = {
          FunctionName = module.create_pr_lambda.lambda_function_arn
          Payload = {
            "projectId.$"   = "$.projectId"
            "branch.$"      = "$.branch"
            "baseBranch.$"  = "$.baseBranch"
            "gitRepo.$"     = "$.gitRepo"
            "gitToken.$"    = "$.gitToken"
            "executionId.$" = "$$.Execution.Id"
          }
        }
        ResultPath = "$.prResult"
        Next       = "RunReviewAgent"
        Catch = [{
          ErrorEquals = ["States.ALL"]
          Next        = "RunReviewAgent"
          ResultPath  = "$.prError"
        }]
      }

      RunReviewAgent = {
        Type     = "Task"
        Resource = "arn:${local.partition}:states:::ecs:runTask.sync"
        Parameters = {
          LaunchType     = "FARGATE"
          Cluster        = var.ecs_cluster_arn
          TaskDefinition = var.agent_task_definition_arn
          NetworkConfiguration = {
            AwsvpcConfiguration = {
              Subnets        = var.private_subnet_ids
              SecurityGroups = [var.agent_security_group_id]
              AssignPublicIp = "DISABLED"
            }
          }
          Overrides = {
            ContainerOverrides = [{
              Name = "agent"
              Environment = [
                { "Name" = "PROJECT_ID", "Value.$" = "$.projectId" },
                { "Name" = "AGENT_TYPE", "Value" = "review" },
                { "Name" = "EXECUTION_ID", "Value.$" = "$$.Execution.Id" },
                { "Name" = "TASK_TOKEN", "Value.$" = "$$.Task.Token" }
              ]
            }]
          }
        }
        ResultPath = "$.reviewResult"
        Next       = "WorkflowSucceeded"
        Catch = [{
          ErrorEquals = ["States.ALL"]
          Next        = "WorkflowFailed"
          ResultPath  = "$.error"
        }]
      }

      WorkflowSucceeded = {
        Type = "Succeed"
      }

      WorkflowFailed = {
        Type  = "Fail"
        Error = "WorkflowFailed"
        Cause = "Agent workflow failed"
      }
    }
  })

  tags = var.tags
}
